### ISSUE TITLE
Update to Version 2021.2

### ISSUE THREAD

**Issue by Floopy-Doo** [vladyslav-burylov/resharper-testlinker2#1]
Hi vladysav
Do you plan to update the compatability of the test linker to the newest version of Rider?
Kind regards
Floopy

**Comment by vladyslav-burylov** [comment]
Hi @Floopy-Doo, I've just pushed update to Jet Brains registry - it should be available soon.

I am really sorry for delay - was busy with some personal activities and immigration to different country.
