### ISSUE TITLE
Notification on new issue

### ISSUE THREAD

**Issue by mu88** [vladyslav-burylov/resharper-testlinker2#10]
Hey @vladyslav-burylov 

Within GitHub's repository settings, is there an option to enable notifications when a new issue is created? Because I neither got an email nor a notification for issue #9

**Comment by vladyslav-burylov** [comment]
Hey @mu88 - yep - it just wants e-mail. Can you send me something to vladyslav.burylov@gmail.com, so that I'll see your e-mail? I will add you.

**Comment by mu88** [comment]
Thx man! I just discovered a step to do this automatically in a GitHub Action and it seems to work well 👍🏻
