### ISSUE TITLE
First automated release

### ISSUE THREAD

**Issue by vladyslav-burylov** [vladyslav-burylov/resharper-testlinker2#6]
Hi @mu88 - FYI - [2021.3 build](https://github.com/vladyslav-burylov/resharper-testlinker2/runs/4460861715?check_suite_focus=true) seems to be failed, however it looks like it was actually uploaded to Jet Brains - I've got confirmation e-mail.

Attaching binary which was uploaded

[testlinker2-2021.3.zip](https://github.com/vladyslav-burylov/resharper-testlinker2/files/7677912/testlinker2-2021.3.zip)

**Comment by vladyslav-burylov** [comment]
BTW - I have slack account inside JetBrains Platform slack namespace, you may reach to me here if you will ever need real-time discussion

My profile: https://jetbrains-platform.slack.com/archives/D01G9C27E4B
How to join: https://plugins.jetbrains.com/slack

**Comment by mu88** [comment]
Ah great to know!

I've modified the publish step so that it won't fail next time (hopefully).

Can you already download the new plugin from JetBrains?

**Comment by vladyslav-burylov** [comment]
Not yet - JetBrains reviewing each update (it takes approximately 1-2 days given my previous experience)

![image](https://user-images.githubusercontent.com/22532819/145259871-9a3ea419-c32e-4acd-aedc-d4d2d5891d41.png)

**Comment by vladyslav-burylov** [comment]
The good news is that binary seems to be OK:

![image](https://user-images.githubusercontent.com/22532819/145260026-86f1956b-3a09-4c74-b646-2c0ad4d43e80.png)

Although, I have no idea how exactly jetBrains verify compatibility

**Comment by vladyslav-burylov** [comment]
@mu88 - I will let you know once plugin will be approved

**Comment by mu88** [comment]
This is good news! I'm curious whether everything is fine :)

Was the proceeding with this release okay for you? Would you prefer a PR-driven approach, e. g. for having a cleaner commit line in `master`?

And do you know whether there is some kind of "staging environment" at JetBrains so that we could test the release procedure without actually creating a "real" new release?

**Comment by vladyslav-burylov** [comment]
Hi mu88

> Was the proceeding with this release okay for you?

For sure - that's exactly why why I given you direct commit permissions - I recently switched to a different tech stack and use .NET occasionally now - so, I'd like to be sure this plugin can be updated w/o my involvement - otherwise there would be delays. Please feel free to continue; I don't see big issue w/r to master branch history simplicity - it's only few people who are looking at this now.

> And do you know whether there is some kind of "staging environment" at JetBrains?

Nope, unfortunately.. Also, I don't see big issue here - within 2-3 Rider updates we should be able to fix all build-script issues and achieve full automation. Moreover - it already works net of github action failures.

p.s. appreciating your contribution - please feel free to add your name to the license :)

**Comment by mu88** [comment]
> For sure - that's exactly why why I given you direct commit permissions

I'm glad to hear 😊

> p.s. appreciating your contribution - please feel free to add your name to the license :)

Ouh thanks a lot, I really do appreciate!

What do you think, let's close this issue?

**Comment by vladyslav-burylov** [comment]
Hi mu88 - yes, I will close it once plugin will be approved

**Comment by vladyslav-burylov** [comment]
Plugin has been approved - closing
