### ISSUE TITLE
Change keyboard shortcut

### ISSUE THREAD

**Issue by mu88** [vladyslav-burylov/resharper-testlinker2#8]
Hey @vladyslav-burylov 

I just recognized that the keyboard shortcut `Ctrl + Shift + I` of the plugin is already in use and therefore doesn't work (at least in Rider 2022.2):
![image](https://user-images.githubusercontent.com/4560672/183870114-5c86baf8-884b-45fe-b495-ab4e24914c9f.png)

What do you think, let's change the keyboard shortcut?

**Comment by vladyslav-burylov** [comment]
Hi @mu88 - I have no objections, just make sure please to use same command ID to make sure people will not be forced to reconfigure shortcuts if they have customizations.

**Comment by mu88** [comment]
`Ctrl + Alt + F7` executes _Go to related files_. What do you think about `Alt + F7` for the plugin?

**Comment by vladyslav-burylov** [comment]
Sounds good, to be honest I’m not the best person to decide which shortcut should be default - it happened historically that I use custom, visual studio based, keyboard schema so I simply don’t know default rider shortcuts
