### ISSUE TITLE
[Rider] Plugin v2022.2.1 does not work while 2022.2.0 does

### ISSUE THREAD

**Issue by EdvardasDlugauskas** [vladyslav-burylov/resharper-testlinker2#9]
Tried the latest version v2022.2.1, but it does not work. Tried the new shortcut, old shortcut, through the context menu. Nothing happens when "Goto linked types" is triggered.

Don't know how to investigate further.

Downgrading to 2022.2 helped - works just fine.

Windows 10, Rider 2022.2.1

**Comment by mu88** [comment]
Hey and sorry about the late response, I was on vacation.

Could you please share your active keymap? Mine looks like this:
![image](https://user-images.githubusercontent.com/4560672/190173148-f5859c87-c252-44cc-ace4-8006322b0f0d.png)

**Comment by EdvardasDlugauskas** [comment]
I called the command from the "commant center" or whatever it's called, by typing the name. So I assumed the keymap wouldn't matter.

I can try reproducing again and sending the keymap screenshot if that helps.

Thanks for your work

**Comment by EdvardasDlugauskas** [comment]
@mu88 

![image](https://user-images.githubusercontent.com/21359162/190994651-f213f5e0-9c20-4b33-9366-4717faca4525.png)

None of the shortcuts work. Manually triggering the command through this search window also doesn't work:
![image](https://user-images.githubusercontent.com/21359162/190994880-357487b5-1076-4a4c-a8d9-8e911d734d82.png)

Version info:
![image](https://user-images.githubusercontent.com/21359162/190994949-95f0ad64-1139-441e-8958-f464b19f7e1d.png)
![image](https://user-images.githubusercontent.com/21359162/190995007-5265f7b4-c856-403d-b838-305a00a78135.png)

**Comment by EdvardasDlugauskas** [comment]
Again, reverting to build 2022.2.0 of the plugin and everything works great

**Comment by mu88** [comment]
Okay, pretty strange 🤔 do you have a sample repo on GitHub so that we can debug it?

@vladyslav-burylov FYI

**Comment by EdvardasDlugauskas** [comment]
No, I don't... 

Might the issue be with some other configuration of the plugin? Maybe it gets reset. Like the test class names to search for.

I call the command, but nothing pops up. Maybe there's a way to see some kind of trace log, to see whether it gets triggered at all? Might provide you with more info

**Comment by mu88** [comment]
No, only the keyboard shortcut was changed.

Unfortunately, the plugin code contains no log statement. But you can try to open the IDE log `idea.log` and look if you see something:
![image](https://user-images.githubusercontent.com/4560672/191010953-c3f3e571-a4f3-4107-9f4b-fecf3050e888.png)

Does the error occur with all Solutions?

**Comment by EdvardasDlugauskas** [comment]
I don't have other Solutions set up to test this.

I tried looking at the logs, here's what I see.

Older plugin version. Seems to initiate the action and log some intermittent results.
![image](https://user-images.githubusercontent.com/21359162/191042188-fafe4c3c-0e0e-4668-b0d6-0f0610f5f242.png)


Newer version - doesn't seem to do anything, just returns:
![image](https://user-images.githubusercontent.com/21359162/191041806-8c08f7af-c523-4839-b3f0-32c0b28255aa.png)

**Comment by mu88** [comment]
Here you go: https://github.com/mu88/Support_TestProject
Please clone the repo, open the solution and see whether the plugin works.

**Comment by NiS0-Maersk** [comment]
I had the same issue on my system, Windows 11, Rider 2022.2.3, latest version of the plugin (2022.2.3)just does not do anything, manually installing 2022.2.0 resolved the issue.

**Comment by mu88** [comment]
Does it work when using _Navigation → Navigate To... → Linked Types_? Also, could you please try whether it works using `Alt Gr + F7`

**Comment by vladyslav-burylov** [comment]
@mu88 - FYI - might be related - this is from the latest update you pushed today:

![image](https://user-images.githubusercontent.com/22532819/200846366-83da3184-e5eb-43e1-8bff-38ad13dcc7a2.png)

> Compatibility verification
Plugins are verified with IntelliJ Plugin Verifier
Verification Results
Rider RD-223.7401.6 (2022.3-EAP7 (eap))Compatible (Restart)
Rider RD-223.7401.6 (2022.3-EAP7 (eap))Not compatible. 2 removed API usages. (Restart)
MethodNotFound: Method not found
The following method was not found: JetBrains.ReSharper.UnitTestFramework.Execution.Launch.UnitTestElements..ctor; Signature: MethodSignature(hasthis MetadataClassType(System.Void) (MetadataClassType(JetBrains.ReSharper.UnitTestFramework.Criteria.IUnitTestElementCriterion), MetadataArrayType(JetBrains.ReSharper.UnitTestFramework.Elements.IUnitTestElement[])))
ReSharperPlugin.TestLinker2.UnitTesting.LinkedTypeUnitTestsDataRuleRegistrar.LinkedTypeUnitTestsDataRule
The following method was not found: JetBrains.ReSharper.Feature.Services.Diagrams.TypeDependencies.TypeDependenciesOptions..ctor; Signature: MethodSignature(hasthis MetadataClassType(System.Void) (MetadataClassType(System.Collections.Generic.ICollection`1[[JetBrains.ReSharper.Feature.Services.Diagrams.TypeDependencies.TypeElementDependencyType, JetBrains.ReSharper.Feature.Services, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325]]), MetadataClassType(System.Func`3[[JetBrains.Application.UI.Diagramming.API.IDiagramGroupNode, JetBrains.Platform.Shell, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325],[JetBrains.Application.UI.Diagramming.API.IDiagramGraph, JetBrains.Platform.Shell, Version=777.0.0.0, Culture=neutral, PublicKeyToken=1010a0d8d6380325],System.Boolean])))
ReSharperPlugin.TestLinker2.Navigation.LinkedTypesSearchDescriptor.get_DiagrammingOptions
Rider RD-222.4459.9 (2022.2.4)Compatible (Restart)
Rider RD-222.4459.9 (2022.2.4)Compatible. (Restart)

**Comment by vladyslav-burylov** [comment]
Though it seems to pass after retry

![image](https://user-images.githubusercontent.com/22532819/200846792-9dc4d64f-20d4-45b2-b32a-7ddfead15d93.png)

**Comment by mu88** [comment]
To be honest, I don't think the messages you received are related to this issue 🤔 but I'll keep it in mind, thx!

Still waiting for the feedback from @NiS0-Maersk / @EdvardasDlugauskas

**Comment by EdvardasDlugauskas** [comment]
> Here you go: https://github.com/mu88/Support_TestProject Please clone the repo, open the solution and see whether the plugin works.

@mu88 I cloned the repo and tried ALT + F7 as well as selecting "Goto Linked Types" from the command center. Does not seem to work.

Rider version 2022.3.1
Test Linker 2 version 2022.3.0.1

**Comment by mu88** [comment]
Which keyboard layout and Windows display language are you using? Mine is:
![image](https://user-images.githubusercontent.com/4560672/214845095-b388a168-7d8e-43ee-bb6f-43075fdd3b91.png)

**Comment by EdvardasDlugauskas** [comment]
Don't know why this matters as triggering through the command center/search bar also doesn't work. And a reminder that it worked in a previous version.

![image](https://user-images.githubusercontent.com/21359162/214856810-3582feb6-7112-4a81-8114-e2b1a54984df.png)

Tried with qwerty, colemak layouts.

**Comment by mu88** [comment]
Unfortunately, I'm not familiar with the JetBrains plugin architecture under the hood :( but maybe the original author can help us, so let's invite him.

@matkoch we'd really appreciate it if you could give us some guidance on how to further analyze this problem. It all started when I tried to resolve #8 with the following two commits:
https://github.com/vladyslav-burylov/resharper-testlinker2/commit/596002dcc4ad81c1d1f6734b287b4b787fc3ee89
https://github.com/vladyslav-burylov/resharper-testlinker2/commit/4823f270ef0feb793781029e24675bdfbc8b7cdf

For some Rider settings, it seems that I somehow broke the plugin, but I can successfully run it on three independent machines I've access to.

**Comment by matkoch** [comment]
Naively, I would recompile against the latest SDK and check again if it solves the issue.

**Comment by mu88** [comment]
I will do so 👍🏻 but to be honest, I'm not very confident that this will solve the issue because a recompilation for 2022.2.1, 2022.2.3, 2022.2.4, and 2022.3 didn't solve it :/

**Comment by mu88** [comment]
Okay @EdvardasDlugauskas , I've recompiled the plugin against `2022.3.1`. Could you please update and let @matkoch and me know if it still fails? Thank you for your help!

**Comment by EdvardasDlugauskas** [comment]
Updated plugin to version 2022.3.1.

Same result, still nothing happens on "Goto Linked Types" or when pressing the hotkey shortcut. Tested in my own project as well as mu88's sample project.

Would be happy to help in some way, as this plugin is one of the most useful ones out there. Saves me a ton of time.

**Comment by mu88** [comment]
Do you have further ideas on how to analyze this, @matkoch ?

**Comment by EdvardasDlugauskas** [comment]
If I understand correctly, the motivation for the change after which it stopped working was done for maintenance purposes? Could we revert it while the issues are being investigated, something like #14 ?

I can't even use the old working plugin version 2022.2.0 anymore, as it's not compatible with 2022.3+. 

Or maybe there's a way for me to get a build of a fork with the #14 changes?

**Comment by EdvardasDlugauskas** [comment]
I see you made the change mentioned in the previous comment.

I will test whether the latest release works once it's out.

**Comment by mu88** [comment]
Yeah exactly, let's give it a try since I have no other clue what to do 🤔
If successful we can close this issue

**Comment by EdvardasDlugauskas** [comment]
Well the fact is that it works now with TestLinker2 version 2022.3.2.

I don't mind closing the issue, thank you.

**Comment by mu88** [comment]
@EdvardasDlugauskas, in the next couple of hours/days, the new version `2022.3.2.1` should be available for download. In this version, I tried to resolve the original issue (the compiler warning) in another way. I'd appreciate it if you could try it if it still works. Thank you!

**Comment by EdvardasDlugauskas** [comment]
@mu88 unfortunately does not work with 2022.3.2.1. 

I tried using the hotkeys. I also tried searching and activating the command "Goto linked types" through the command center. The action was found, but clicking on it didn't do anything.

Reverting to plugin version 2022.3.2 fixes the issue.

**Comment by mu88** [comment]
Thanks @EdvardasDlugauskas , I'll get in contact with JetBrains again and keep you posted.

**Comment by mu88** [comment]
@EdvardasDlugauskas , can you please have another look into the logs as you did it [here](https://github.com/vladyslav-burylov/resharper-testlinker2/issues/9#issuecomment-1251106264)?

**Comment by mu88** [comment]
@EdvardasDlugauskas when looking into the logs, can you please run Rider in [Internal Mode](https://rider-support.jetbrains.com/hc/en-us/articles/207327910-How-to-run-JetBrains-Rider-in-Internal-Mode)? The JetBrains guys recommend doing so to see whether there are any exceptions.

**Comment by mu88** [comment]
I'm closing this issue due to missing feedback - feel free to come back to it later :)

**Comment by EdvardasDlugauskas** [comment]
I will update the thread when a new update comes out and the extension stops working for me again... Right now using the 2022.3.2 version and didn't have enough motivation to collect all of the logs

Thank you for your work

**Comment by EdvardasDlugauskas** [comment]
@mu88 I tried running in Internal Mode, looked around, did not notice anything related to the issue. But I did not have any clue where to look, so might have missed something.

I took a look at the logs again. Here is what I see after trying to click "Goto Linked Types" in the command bar:

    12:55:28.447 |V| RiderActions                  | :1                 | Started 'GotoLinkedTypes2Action' action. Attempt: 1.
    12:55:28.448 |I| RiderActions                  | :1                 | 'GotoLinkedTypes2Action' Action execution failed. Action '$GotoLinkedTypes2Action' execution failed: Action '$GotoLinkedTypes2Action' not found


![image](https://github.com/vladyslav-burylov/resharper-testlinker2/assets/21359162/ece66208-5c79-46e8-a5fc-fe9ee526a067)

Current setup:
- Rider Build #RD-232.8660.212, built on July 31, 2023
- 2023.2.0

**Comment by mu88** [comment]
Since Rider will include the features of this plugin natively with 2023.3, I suggest you wait until then
